resources:
  repositories:
   - repository: SeleniumJavaMaven
     type: github
     endpoint: https://github.com/Lucifer12598/Jenkins2ADO
     name: Lucifer12598/Jenkins2ADO
     ref: main
trigger:
  - master
pool:
  vmImage: ubuntu-latest
steps:
  - task: Maven@3
    inputs:
      mavenPomFile: SeleniumJavaMaven/pom.xml
      mavenOptions: -Xmx3072m
      javaHomeOption: JDKVersion
      jdkVersionOption: "11"
      jdkArchitectureOption: x64
      publishJUnitResults: true
      testResultsFiles: "**/surefire-reports/TEST-*.xml"
      goals: clean test
